language: go
sudo: required
install: true
notifications:
  email: false
go:
  - 1.9.x
  - master
before_script:
  - cd /tmp
  - curl -L https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz -o nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz
  - tar -zxvf nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz
  - sudo cp -R nsq-1.0.0-compat.linux-amd64.go1.8/bin/. /usr/local/bin
  - nsqlookupd &
  - nsqd -lookupd-tcp-address localhost:4160 &
  - sleep 1
  - echo 'test' | to_nsq -nsqd-tcp-address localhost:4150 -topic test -rate 2
  - cd $HOME/gopath/src/github.com/adamweiner/nsqd-prometheus-exporter
script:
  - make
  - ./nsqd-prometheus-exporter &
  - sleep 1
  - curl -s localhost:30000/metrics > metrics.out
  - cat metrics.out
  - cat metrics.out | grep 'nsqd_depth{channel="",paused="false",topic="test",type="topic"} 1'
