language: go
sudo: required
install: true
notifications:
  email: false
go:
  - 1.9.x
  - master
script:
  # build nsqd-prometheus-exporter
  - make
  # test with NSQ 0.3.8
  - ./test/install_nsq_0.3.8.sh
  - ./nsqd-prometheus-exporter &
  - sleep 1
  - ./test/test_depth_metric.sh
  # clean up
  - sudo killall -v nsqlookupd nsqd nsqd-prometheus-exporter
  - sudo rm -fv /usr/local/bin/*nsq*
  # test with NSQ 1.0.0
  - ./test/install_nsq_1.0.0.sh
  - ./nsqd-prometheus-exporter &
  - sleep 1
  - curl localhost:4151
  - ./test/test_depth_metric.sh
