language: go
sudo: required
install: true
go:
  - 1.8.x
  - master
before_script:
  - curl https://github.com/nsqio/nsq/releases/download/v0.3.8/nsq-0.3.8.linux-amd64.go1.6.2.tar.gz -o /tmp/nsq-0.3.8.linux-amd64.go1.6.2.tar.gz
  - tar -zxvf /tmp/nsq-0.3.8.linux-amd64.go1.6.2.tar.gz
  - sudo cp -R /tmp/nsq-0.3.8.linux-amd64.go1.6.2/bin/. /usr/local/bin
  - nsqlookupd &
  - nsqd -lookupd-tcp-address localhost:4160 &
  - echo 'test' > to_nsq -nsqd-tcp-address localhost:4150 -topic test
script:
  - go env
  - make
  - ./nsqd-prometheus-exporter &
  - sleep 1; curl localhost:3000
